import type { DailyTaskTemplate, WeeklyTaskTemplate } from './types';

export const DEFAULT_DAILY_TEMPLATES: DailyTaskTemplate[] = [
  {
    id: 'tpl-moments',
    enabled: true,
    taskKey: 'moments_post',
    taskName: '朋友圈发布',
    taskType: '运营',
    description: '每日发布朋友圈，上传截图并选择内容类型。',
    completionMethod: '上传朋友圈截图 + 选择发布类型 + 标记完成',
    targetCount: 1,
    needProof: true,
    needReview: false,
    kpiCounted: true,
    showInCenter: true,
    endOfDayDeadline: true,
  },
  {
    id: 'tpl-calls',
    enabled: true,
    taskKey: 'calls_three',
    taskName: '电联客户3个以上',
    taskType: '电联',
    description: '登记电联记录，系统按当日记录条数统计，达到 3 条自动满足数量。',
    completionMethod: '填写电联客户记录（本页「留资/电联跟进区」同步）',
    targetCount: 3,
    needProof: false,
    needReview: false,
    kpiCounted: true,
    showInCenter: true,
    endOfDayDeadline: true,
  },
  {
    id: 'tpl-daily-sales',
    enabled: true,
    taskKey: 'daily_sales_report',
    taskName: '日报：每日销售额数据',
    taskType: '日报',
    description: '填写核心日报字段；与「留资跟进表 → 日报/询单量登记」联动，保存日报后即视为已完成。',
    completionMethod: '留资跟进表 · 日报/询单量登记（与本页字段同步）',
    targetCount: 1,
    needProof: false,
    needReview: false,
    kpiCounted: true,
    showInCenter: true,
    endOfDayDeadline: true,
  },
  {
    id: 'tpl-review-table',
    enabled: true,
    taskKey: 'review_register',
    taskName: '评价表格登记',
    taskType: '评价',
    description: '登记评价并上传截图；开启审核时提交后为待审核。',
    completionMethod: '填写评价记录 + 上传截图',
    targetCount: 1,
    needProof: true,
    needReview: true,
    kpiCounted: true,
    showInCenter: true,
    endOfDayDeadline: true,
  },
  {
    id: 'tpl-data-summary',
    enabled: true,
    taskKey: 'data_summary_sheet',
    taskName: '《数据汇总登记表》--售前销售分表',
    taskType: '表格',
    description: '外链或勾选已填，可上传截图佐证。',
    completionMethod: '表格链接 + 勾选已填 + 可选截图',
    targetCount: 1,
    needProof: false,
    needReview: false,
    kpiCounted: true,
    showInCenter: true,
    endOfDayDeadline: true,
  },
  {
    id: 'tpl-presale-receipt',
    enabled: true,
    taskKey: 'presale_daily_receipt',
    taskName: '【售前客服】日工作回执--个人日销+询单量+个人留咨分表',
    taskType: '回执',
    description: '个人留咨分表与跟进；与「留资跟进表 → 今日留资登记」联动，有当日留资记录即视为已完成。',
    completionMethod: '留资跟进表 · 今日留资登记',
    targetCount: 1,
    needProof: false,
    needReview: false,
    kpiCounted: true,
    showInCenter: true,
    endOfDayDeadline: true,
  },
  {
    id: 'tpl-douyin',
    enabled: true,
    taskKey: 'douyin_leads_follow',
    taskName: '抖音留资信息跟踪--留咨电话客服有没有电联',
    taskType: '留资',
    description: '登记抖音留资客户及是否已电联；与「留资跟进表 → 抖音留资电联跟踪」联动。',
    completionMethod: '留资跟进表 · 抖音留资电联跟踪',
    targetCount: 1,
    needProof: false,
    needReview: false,
    kpiCounted: true,
    showInCenter: true,
    endOfDayDeadline: true,
  },
];

export const DEFAULT_WEEKLY_TEMPLATES: WeeklyTaskTemplate[] = [
  {
    id: 'wtpl-competitor',
    enabled: true,
    taskName: '竞品聊天',
    targetCount: 3,
    requiredCategories: [
      { key: '单室真空机', label: '单室真空机', minCount: 1 },
      { key: '双室真空机', label: '双室真空机', minCount: 1 },
      { key: '封箱机', label: '封箱机', minCount: 1 },
    ],
    needProof: true,
    needReview: false,
  },
];
