import type { TodayTaskState } from './types';
import { loadTodayTasks } from './storage';

const DEMO_STAFF = ['周晨', '陶柳青'];

export function getInitialTaskState(): TodayTaskState {
  const s = loadTodayTasks();
  if (s.templates.length > 0 || s.assignments.length > 0) return s;
  const t = new Date().toISOString();
  return {
    templates: [
      {
        id: 'tpl-welcome',
        name: '标准日班（示例）',
        description: '可在「任务模板」中编辑或删除',
        defaultPriority: 'P2',
        completionMode: 'checkbox',
        createdAt: t,
      },
    ],
    assignments: [
      {
        id: 'asg-day-01',
        title: '查看昨日未回复客户',
        description: '在客服后台筛选「昨日未回复」，逐条处理或标记跟进。',
        taskType: '复盘',
        staffNames: DEMO_STAFF,
        recurrence: 'daily',
        startTime: '08:00',
        endTime: '08:30',
        priority: 'P2',
        completionMode: 'checkbox',
        quantityTarget: 1,
        shiftLabel: '早间',
        shiftCode: 'day',
        active: true,
        kpiTag: false,
        createdBy: '示例数据',
        createdAt: t,
        updatedAt: t,
      },
      {
        id: 'asg-day-02',
        title: '整理今日重点跟进客户名单',
        description: '结合跟进表与询单表，列出今日必联系的高意向客户。',
        taskType: '准备',
        staffNames: DEMO_STAFF,
        recurrence: 'daily',
        startTime: '08:30',
        endTime: '09:00',
        priority: 'P1',
        completionMode: 'screenshot',
        quantityTarget: 1,
        shiftLabel: '早间',
        shiftCode: 'day',
        active: true,
        kpiTag: false,
        createdBy: '示例数据',
        createdAt: t,
        updatedAt: t,
      },
      {
        id: 'asg-day-03',
        title: '高意向客户电联追单',
        description: '对名单内客户外呼，记录意向与下次跟进时间。',
        taskType: '电联',
        staffNames: DEMO_STAFF,
        recurrence: 'daily',
        startTime: '09:00',
        endTime: '10:00',
        priority: 'P0',
        completionMode: 'quantity',
        quantityTarget: 5,
        shiftLabel: '上午',
        shiftCode: 'day',
        active: true,
        kpiTag: true,
        createdBy: '示例数据',
        createdAt: t,
        updatedAt: t,
      },
      {
        id: 'asg-day-04',
        title: '售前接待与留资引导',
        description: '接待店铺/私域咨询，完成留资与标签录入。',
        taskType: '售前',
        staffNames: DEMO_STAFF,
        recurrence: 'daily',
        startTime: '10:00',
        endTime: '11:30',
        priority: 'P1',
        completionMode: 'quantity',
        quantityTarget: 8,
        shiftLabel: '上午',
        shiftCode: 'day',
        active: true,
        kpiTag: true,
        createdBy: '示例数据',
        createdAt: t,
        updatedAt: t,
      },
      {
        id: 'asg-day-05',
        title: '上传AI话术案例',
        description: '截取一段有效对话或话术，上传截图并附一句说明。',
        taskType: 'AI运用',
        staffNames: DEMO_STAFF,
        recurrence: 'daily',
        startTime: '11:30',
        endTime: '12:00',
        priority: 'P3',
        completionMode: 'screenshot',
        quantityTarget: 1,
        shiftLabel: '午间',
        shiftCode: 'day',
        active: true,
        kpiTag: false,
        createdBy: '示例数据',
        createdAt: t,
        updatedAt: t,
      },
      {
        id: 'asg-day-06',
        title: '报价客户追单',
        description: '对已报价未成交客户进行跟进，备注客户编号或昵称。',
        taskType: '追单',
        staffNames: DEMO_STAFF,
        recurrence: 'daily',
        startTime: '14:00',
        endTime: '15:00',
        priority: 'P0',
        completionMode: 'customer',
        quantityTarget: 1,
        shiftLabel: '下午',
        shiftCode: 'day',
        active: true,
        kpiTag: true,
        createdBy: '示例数据',
        createdAt: t,
        updatedAt: t,
      },
      {
        id: 'asg-day-07',
        title: '引导客户评价',
        description: '邀请已成交或高满意客户完成评价，填写完成条数。',
        taskType: '评价',
        staffNames: DEMO_STAFF,
        recurrence: 'daily',
        startTime: '16:00',
        endTime: '17:00',
        priority: 'P2',
        completionMode: 'quantity',
        quantityTarget: 3,
        shiftLabel: '下午',
        shiftCode: 'day',
        active: true,
        kpiTag: false,
        createdBy: '示例数据',
        createdAt: t,
        updatedAt: t,
      },
      {
        id: 'asg-day-08',
        title: '今日KPI数据上传',
        description: '在 KPI 模块或本任务中提交当日关键数据说明。',
        taskType: 'KPI上传',
        staffNames: DEMO_STAFF,
        recurrence: 'daily',
        startTime: '17:00',
        endTime: '17:30',
        priority: 'P1',
        completionMode: 'daily_report',
        quantityTarget: 1,
        shiftLabel: '日终',
        shiftCode: 'day',
        active: true,
        kpiTag: true,
        requiresSupervisorReview: false,
        createdBy: '示例数据',
        createdAt: t,
        updatedAt: t,
      },
      {
        id: 'asg-review-demo',
        title: '【示例】日终小结（需主管审核）',
        description: '填写小结后提交，主管在「主管看板」中审核。',
        taskType: '审核',
        staffNames: DEMO_STAFF,
        recurrence: 'daily',
        startTime: '17:30',
        endTime: '18:30',
        priority: 'P2',
        completionMode: 'daily_report',
        quantityTarget: 1,
        shiftLabel: '晚班',
        shiftCode: 'night',
        active: true,
        kpiTag: true,
        requiresSupervisorReview: true,
        createdBy: '示例数据',
        createdAt: t,
        updatedAt: t,
      },
    ],
    completions: {},
  };
}
