import type {
  KpiDataMappingRow,
  KpiFormulaConfigRow,
  KpiIndicatorConfigRow,
  KpiScoreRuleRow,
  KpiTargetConfigRow,
  KpiWarningRuleRow,
} from './types';

function rid() {
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) return crypto.randomUUID();
  return `${Date.now()}-${Math.random().toString(36).slice(2, 11)}`;
}

export function defaultKpiIndicators(): KpiIndicatorConfigRow[] {
  const rows: Omit<KpiIndicatorConfigRow, 'id'>[] = [
    { enabled: true, sortOrder: 0, name: '咨询量', code: 'inquiryCount', indicatorType: 'count', statPeriod: 'daily', statSubject: 'employee_store', weight: 1, displayFormat: 'number', remark: '' },
    { enabled: true, sortOrder: 1, name: '留资数', code: 'leadCount', indicatorType: 'count', statPeriod: 'daily', statSubject: 'employee_store', weight: 1, displayFormat: 'number', remark: '' },
    { enabled: true, sortOrder: 2, name: '留资率', code: 'leadRate', indicatorType: 'ratio', statPeriod: 'daily', statSubject: 'employee_store', weight: 1, displayFormat: 'percent', remark: '' },
    { enabled: true, sortOrder: 3, name: '电联完成率', code: 'callCompletionRate', indicatorType: 'ratio', statPeriod: 'daily', statSubject: 'employee', weight: 1, displayFormat: 'percent', remark: '抖音留资口径为主' },
    { enabled: true, sortOrder: 4, name: '销售额', code: 'salesAmount', indicatorType: 'amount', statPeriod: 'daily', statSubject: 'employee_store', weight: 1, displayFormat: 'amount', remark: '日报合计优先' },
    { enabled: true, sortOrder: 5, name: '销售额完成率', code: 'salesCompletionRate', indicatorType: 'ratio', statPeriod: 'monthly', statSubject: 'employee_store', weight: 1, displayFormat: 'percent', remark: '需配置月度目标' },
    { enabled: true, sortOrder: 6, name: '有效评价数', code: 'reviewScoreCount', indicatorType: 'weighted', statPeriod: 'daily', statSubject: 'employee_store', weight: 1, displayFormat: 'number', remark: '' },
    { enabled: true, sortOrder: 7, name: 'AI使用', code: 'aiUsage', indicatorType: 'weighted', statPeriod: 'daily', statSubject: 'employee', weight: 1, displayFormat: 'number', remark: '话术×2 + 案例×3 + 次数×1' },
    { enabled: true, sortOrder: 8, name: '老客户回访完成率', code: 'oldCustomerFollowRate', indicatorType: 'ratio', statPeriod: 'daily', statSubject: 'employee', weight: 1, displayFormat: 'percent', remark: '' },
  ];
  return rows.map((r, i) => ({ ...r, id: rid(), sortOrder: i }));
}

/** 内置数据源映射（可按需增删） */
export function defaultKpiDataMappings(): KpiDataMappingRow[] {
  const phoneOrWechat = JSON.stringify([
    { field: 'phone', op: 'notEmpty' },
    { field: 'customerWechat', op: 'notEmpty' },
    { field: 'hasAddedWechat', op: 'eq', value: true },
  ]);
  const rows: Omit<KpiDataMappingRow, 'id'>[] = [
    {
      enabled: true,
      sortOrder: 0,
      metricCode: 'inquiryCount',
      sourceModule: '日报/询单量登记',
      sourceKey: 'daily_inquiry_reports',
      field: 'inquiryCount',
      aggregateType: 'sum',
      matchDate: 'date',
      matchEmployee: 'employeeName',
      matchStore: 'storeName',
      dedupeFields: '',
      validRulesJson: '[]',
      onlyApproved: false,
      auditStatusField: '',
      approvedValue: '',
      extraJson: '',
      remark: '咨询量合计',
    },
    {
      enabled: true,
      sortOrder: 1,
      metricCode: 'leadCount',
      sourceModule: '留资跟进表',
      sourceKey: 'lead_follow_records',
      field: '',
      aggregateType: 'count',
      matchDate: 'date',
      matchEmployee: 'employeeName',
      matchStore: 'storeName',
      dedupeFields: 'customerPlatformId,phone,customerWechat,storeName',
      validRulesJson: phoneOrWechat,
      onlyApproved: false,
      auditStatusField: '',
      approvedValue: '',
      extraJson: JSON.stringify({ validMode: 'or' }),
      remark: '有效留资：电话/微信/已加微，去重',
    },
    {
      enabled: true,
      sortOrder: 2,
      metricCode: 'salesAmount',
      sourceModule: '日报/询单量登记',
      sourceKey: 'daily_inquiry_reports',
      field: 'dailySalesAmount',
      aggregateType: 'sum',
      matchDate: 'date',
      matchEmployee: 'employeeName',
      matchStore: 'storeName',
      dedupeFields: '',
      validRulesJson: '[]',
      onlyApproved: false,
      auditStatusField: '',
      approvedValue: '',
      extraJson: JSON.stringify({ role: 'primary_sales' }),
      remark: '主口径：日报销售额合计',
    },
    {
      enabled: true,
      sortOrder: 3,
      metricCode: 'salesAmount',
      sourceModule: '留资跟进表',
      sourceKey: 'lead_follow_records',
      field: 'dealAmount',
      aggregateType: 'sum',
      matchDate: 'date',
      matchEmployee: 'employeeName',
      matchStore: 'storeName',
      dedupeFields: '',
      validRulesJson: JSON.stringify([{ field: 'isDeal', op: 'eq', value: true }]),
      onlyApproved: false,
      auditStatusField: '',
      approvedValue: '',
      extraJson: JSON.stringify({ role: 'fallback_sales' }),
      remark: '仅当日报销售额为空时回退',
    },
    {
      enabled: true,
      sortOrder: 4,
      metricCode: 'calledCount',
      sourceModule: '留资跟进表',
      sourceKey: 'lead_follow_records',
      field: '',
      aggregateType: 'count',
      matchDate: 'date',
      matchEmployee: 'employeeName',
      matchStore: 'storeName',
      dedupeFields: 'phone',
      validRulesJson: JSON.stringify([{ field: 'firstCallDate', op: 'notEmpty' }]),
      onlyApproved: false,
      auditStatusField: '',
      approvedValue: '',
      extraJson: '',
      remark: '已首电留资',
    },
    {
      enabled: true,
      sortOrder: 5,
      metricCode: 'calledCount',
      sourceModule: '抖音留资电联跟踪',
      sourceKey: 'douyin_lead_follow_records',
      field: '',
      aggregateType: 'count',
      matchDate: 'date',
      matchEmployee: 'employeeName',
      matchStore: '',
      dedupeFields: 'phone,customerName',
      validRulesJson: JSON.stringify([{ field: 'hasCalled', op: 'eq', value: true }]),
      onlyApproved: false,
      auditStatusField: '',
      approvedValue: '',
      extraJson: '',
      remark: '与留资首电并集（预览按系统汇总口径展示）',
    },
    {
      enabled: true,
      sortOrder: 6,
      metricCode: 'requiredCallCount',
      sourceModule: '抖音留资电联跟踪',
      sourceKey: 'douyin_lead_follow_records',
      field: '',
      aggregateType: 'count',
      matchDate: 'date',
      matchEmployee: 'employeeName',
      matchStore: '',
      dedupeFields: 'phone,customerName',
      validRulesJson: '[]',
      onlyApproved: false,
      auditStatusField: '',
      approvedValue: '',
      extraJson: '',
      remark: '当日抖音应电联条数（与业务页一致）',
    },
    {
      enabled: true,
      sortOrder: 7,
      metricCode: 'reviewScoreCount',
      sourceModule: '评价管理',
      sourceKey: 'review_register_records',
      field: 'reviewType',
      aggregateType: 'weighted',
      matchDate: 'date',
      matchEmployee: 'staffName',
      matchStore: 'shop',
      dedupeFields: '',
      validRulesJson: '[]',
      onlyApproved: true,
      auditStatusField: 'status',
      approvedValue: 'completed',
      extraJson: JSON.stringify({
        reviewDecisionApproved: true,
        weights: { text: 1, image: 1.5, video: 2, follow: 1 },
        typeDetect: 'reviewType',
      }),
      remark: '仅统计已通过；文字1/图1.5/视频2/追评1',
    },
    {
      enabled: true,
      sortOrder: 8,
      metricCode: 'aiUsage',
      sourceModule: 'AI运用反馈',
      sourceKey: 'ai_usage_records',
      field: '',
      aggregateType: 'weighted',
      matchDate: 'date',
      matchEmployee: 'employeeName',
      matchStore: '',
      dedupeFields: '',
      validRulesJson: '[]',
      onlyApproved: false,
      auditStatusField: '',
      approvedValue: '',
      extraJson: JSON.stringify({ use: 1, script: 2, case: 3, fields: { use: 'aiUseCount', script: 'aiScriptCount', case: 'aiCaseCount' } }),
      remark: 'aiUseCount×1 + aiScriptCount×2 + aiCaseCount×3',
    },
    {
      enabled: true,
      sortOrder: 9,
      metricCode: 'oldCustomerFollowRate',
      sourceModule: '老客户CRM',
      sourceKey: 'old_customer_follow_tasks',
      field: '',
      aggregateType: 'formula',
      matchDate: 'followDate',
      matchEmployee: 'ownerEmployee',
      matchStore: '',
      dedupeFields: '',
      validRulesJson: '[]',
      onlyApproved: false,
      auditStatusField: '',
      approvedValue: '',
      extraJson: JSON.stringify({ numerator: 'isCompleted:true', denominator: 'all' }),
      remark: '完成数/任务数',
    },
    {
      enabled: true,
      sortOrder: 10,
      metricCode: 'socialPostCount',
      sourceModule: '朋友圈/视频号',
      sourceKey: 'social_post_records',
      field: '',
      aggregateType: 'count',
      matchDate: 'date',
      matchEmployee: 'employeeName',
      matchStore: '',
      dedupeFields: '',
      validRulesJson: '[]',
      onlyApproved: false,
      auditStatusField: '',
      approvedValue: '',
      extraJson: '',
      remark: '可选 LS',
    },
    {
      enabled: true,
      sortOrder: 11,
      metricCode: 'repurchaseAmount',
      sourceModule: '复购跟踪',
      sourceKey: 'repurchase_opportunities',
      field: 'actualAmount',
      aggregateType: 'sum',
      matchDate: '',
      matchEmployee: 'ownerEmployee',
      matchStore: '',
      dedupeFields: '',
      validRulesJson: JSON.stringify([{ field: 'repurchaseStatus', op: 'eq', value: '已复购' }]),
      onlyApproved: false,
      auditStatusField: '',
      approvedValue: '',
      extraJson: '',
      remark: '已复购金额',
    },
  ];
  return rows.map((r, i) => ({ ...r, id: rid(), sortOrder: i }));
}

export function defaultKpiFormulas(): KpiFormulaConfigRow[] {
  const rows: Omit<KpiFormulaConfigRow, 'id'>[] = [
    { enabled: true, sortOrder: 0, metricCode: 'leadRate', expression: 'leadCount / inquiryCount', displayFormat: 'percent', remark: '' },
    { enabled: true, sortOrder: 1, metricCode: 'callCompletionRate', expression: 'calledCount / requiredCallCount', displayFormat: 'percent', remark: '分母为0时无值' },
    { enabled: true, sortOrder: 2, metricCode: 'salesCompletionRate', expression: 'salesAmount / monthlyTarget_salesAmount', displayFormat: 'percent', remark: '依赖 kpi_target_configs 月度目标' },
  ];
  return rows.map((r, i) => ({ ...r, id: rid(), sortOrder: i }));
}

export function defaultKpiScoreRules(): KpiScoreRuleRow[] {
  const codes = ['inquiryCount', 'leadCount', 'leadRate', 'callCompletionRate', 'salesAmount', 'salesCompletionRate', 'reviewScoreCount', 'aiUsage', 'oldCustomerFollowRate'];
  return codes.map((metricCode, i) => ({
    id: rid(),
    enabled: true,
    sortOrder: i,
    metricCode,
    fullScoreAtRate: 1,
    capRatio: 1.2,
    warnBelowRate: 0.8,
    criticalBelowRate: 0.6,
    allowOverBonus: false,
    remark: '达到100%满分；封顶120%；低于80%预警；低于60%严重',
  }));
}

export function defaultKpiWarningRules(): KpiWarningRuleRow[] {
  const rows: Omit<KpiWarningRuleRow, 'id'>[] = [
    { enabled: true, sortOrder: 0, metricCode: 'leadRate', condition: 'lt:0.2', severity: 'warn', message: '留资率偏低', remark: '' },
    { enabled: true, sortOrder: 1, metricCode: 'callCompletionRate', condition: 'lt:0.8', severity: 'warn', message: '今日电联未完成', remark: '' },
    { enabled: true, sortOrder: 2, metricCode: 'salesCompletionRate', condition: 'lt_progress:0.8', severity: 'warn', message: '销售额进度落后', remark: '与时间进度对比需目标配置' },
    { enabled: true, sortOrder: 3, metricCode: 'aiUsage', condition: 'eq:0', severity: 'info', message: 'AI使用未提交', remark: '' },
    { enabled: true, sortOrder: 4, metricCode: 'reviewScoreCount', condition: 'lt_progress:0.7', severity: 'warn', message: '评价引导不足', remark: '' },
  ];
  return rows.map((r, i) => ({ ...r, id: rid(), sortOrder: i }));
}

export function defaultKpiTargets(): KpiTargetConfigRow[] {
  return [];
}
