'use client';
import { useMemo, useState } from 'react';

export default function Page(){
  const [rows,setRows]=useState<any[]>([]);
  const [f,setF]=useState({shop:'天猫旗舰店',staff:'周晨',reception:0,aftersale:0,invalidInquiry:0,presale:0,deals:0,sales:0});
  const add=()=>setRows([{...f,date:new Date().toISOString().slice(0,10)},...rows]);
  const total = useMemo(()=>rows.reduce((s,r)=>s+Number(r.sales||0),0),[rows]);
  return <div className='space-y-3'><h2 className='text-xl font-semibold'>每日销售额数据（个人日销）</h2><div className='bg-white border rounded p-3 grid grid-cols-4 gap-2'><input className='border p-2' placeholder='店铺' value={f.shop} onChange={e=>setF({...f,shop:e.target.value})}/><input className='border p-2' placeholder='姓名' value={f.staff} onChange={e=>setF({...f,staff:e.target.value})}/><input className='border p-2' placeholder='接待人数' type='number' value={f.reception} onChange={e=>setF({...f,reception:Number(e.target.value)})}/><input className='border p-2' placeholder='售后人数' type='number' value={f.aftersale} onChange={e=>setF({...f,aftersale:Number(e.target.value)})}/><input className='border p-2' placeholder='无效询单' type='number' value={f.invalidInquiry} onChange={e=>setF({...f,invalidInquiry:Number(e.target.value)})}/><input className='border p-2' placeholder='售前人数' type='number' value={f.presale} onChange={e=>setF({...f,presale:Number(e.target.value)})}/><input className='border p-2' placeholder='成交人数' type='number' value={f.deals} onChange={e=>setF({...f,deals:Number(e.target.value)})}/><input className='border p-2' placeholder='日销售额' type='number' value={f.sales} onChange={e=>setF({...f,sales:Number(e.target.value)})}/><button className='bg-blue-600 text-white px-3 py-1 rounded col-span-4' onClick={add}>提交</button></div><div className='bg-white border rounded p-3'>今日提交情况：{rows.length} 条；数据明细总销售额：¥{total}</div><div className='bg-white border rounded p-3 overflow-auto'><table className='w-full text-sm'><thead><tr><th>日期</th><th>店铺</th><th>接待</th><th>售后</th><th>无效询单</th><th>售前</th><th>成交</th><th>日销</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i} className='border-t'><td>{r.date}</td><td>{r.shop}</td><td>{r.reception}</td><td>{r.aftersale}</td><td>{r.invalidInquiry}</td><td>{r.presale}</td><td>{r.deals}</td><td>{r.sales}</td></tr>)}</tbody></table></div></div>
}
