'use client';
import { useEffect, useMemo, useState } from 'react';

export default function Page(){
  const today = new Date().toISOString().slice(0,10);
  const [date,setDate]=useState(today); const [staff,setStaff]=useState('周晨');
  const [leads,setLeads]=useState<any[]>([]); const [logs,setLogs]=useState<any[]>([]); const [acts,setActs]=useState<any[]>([]);
  const [opts,setOpts]=useState<any>({shops:['天猫旗舰店'],inquiry_types:['真空机'],customer_types:['新客户'],status_options:['待跟进'],lost_reasons:['价格高']});
  const [leadForm,setLeadForm]=useState({shop:'天猫旗舰店',inquiryType:'真空机',model:'',customerType:'新客户',buyerId:'',phone:'',wechat:'',wechatAdded:true,holdSent:false,intentLevel:'',tier:'',note:''});
  const [logForm,setLogForm]=useState({shop:'天猫旗舰店',buyerId:'',status:'待跟进',statusNote:'',isDeal:false,dealAmount:'',lostReason:'',nextAction:''});
  const load=async()=>{setLeads(await (await fetch(`/api/leads?date=${date}`)).json());setLogs(await (await fetch(`/api/followup-logs?date=${date}`)).json());setActs(await (await fetch(`/api/daily-activity?date=${date}`)).json())};
  useEffect(()=>{load();fetch('/api/options').then(r=>r.json()).then((o)=>{setOpts(o);setLeadForm(v=>({...v,shop:o.shops?.[0]||v.shop,inquiryType:o.inquiry_types?.[0]||v.inquiryType,customerType:o.customer_types?.[0]||v.customerType}));setLogForm(v=>({...v,status:o.status_options?.[0]||v.status,shop:o.shops?.[0]||v.shop,lostReason:o.lost_reasons?.[0]||v.lostReason}));});},[date]);
  const submitLead=async()=>{const r=await fetch('/api/leads',{method:'POST',body:JSON.stringify({...leadForm,date,staff})});if(!r.ok)return alert(await r.text());setLeadForm({...leadForm,model:'',buyerId:'',phone:'',wechat:''});load();};
  const submitLog=async()=>{const r=await fetch('/api/followup-logs',{method:'POST',body:JSON.stringify({...logForm,date,staff,dealAmount:logForm.dealAmount?Number(logForm.dealAmount):null})});if(!r.ok)return alert(await r.text());setLogForm({...logForm,buyerId:'',dealAmount:'',lostReason:''});load();};
  const metrics=useMemo(()=>{const totalLeads=leads.length;const totalF=logs.length;const dealLogs=logs.filter((x:any)=>x.isDeal);const dealCnt=dealLogs.length;const dealAmt=dealLogs.reduce((s:number,x:any)=>s+Number(x.dealAmount||0),0);return {totalLeads,totalF,dealCnt,dealAmt,conv:totalLeads?dealCnt/totalLeads*100:0,aov:dealCnt?dealAmt/dealCnt:0}},[leads,logs]);
  return <div className='space-y-4'><h2 className='text-xl font-semibold'>询单转化（兼容原PY版）</h2><div className='flex gap-2'><input type='date' className='border p-2' value={date} onChange={e=>setDate(e.target.value)}/><input className='border p-2' value={staff} onChange={e=>setStaff(e.target.value)} placeholder='客服姓名'/></div>
  <div className='grid grid-cols-6 gap-2 text-sm'>{[['线索',metrics.totalLeads],['跟进',metrics.totalF],['成交单',metrics.dealCnt],['成交额',metrics.dealAmt],['转化率',metrics.conv.toFixed(2)+'%'],['客单价',metrics.aov.toFixed(0)]].map(([k,v])=><div key={String(k)} className='bg-white border rounded p-3'><div>{k}</div><div className='font-bold'>{String(v)}</div></div>)}</div>
  <div className='grid grid-cols-2 gap-3'><div className='bg-white border rounded p-3 space-y-2'><h3>①线索主档</h3><select className='border p-2 w-full' value={leadForm.shop} onChange={e=>setLeadForm({...leadForm,shop:e.target.value})}>{(opts.shops||[]).map((x:string)=><option key={x}>{x}</option>)}</select><select className='border p-2 w-full' value={leadForm.inquiryType} onChange={e=>setLeadForm({...leadForm,inquiryType:e.target.value})}>{(opts.inquiry_types||[]).map((x:string)=><option key={x}>{x}</option>)}</select><input className='border p-2 w-full' placeholder='产品型号*' value={leadForm.model} onChange={e=>setLeadForm({...leadForm,model:e.target.value})}/><input className='border p-2 w-full' placeholder='旺旺ID*' value={leadForm.buyerId} onChange={e=>setLeadForm({...leadForm,buyerId:e.target.value})}/><input className='border p-2 w-full' placeholder='电话' value={leadForm.phone} onChange={e=>setLeadForm({...leadForm,phone:e.target.value})}/><input className='border p-2 w-full' placeholder='微信' value={leadForm.wechat} onChange={e=>setLeadForm({...leadForm,wechat:e.target.value})}/><button className='bg-blue-600 text-white px-3 py-1 rounded' onClick={submitLead}>提交留资</button></div>
  <div className='bg-white border rounded p-3 space-y-2'><h3>②跟进日志</h3><input className='border p-2 w-full' placeholder='旺旺ID*' value={logForm.buyerId} onChange={e=>setLogForm({...logForm,buyerId:e.target.value})}/><select className='border p-2 w-full' value={logForm.status} onChange={e=>setLogForm({...logForm,status:e.target.value})}>{(opts.status_options||[]).map((x:string)=><option key={x}>{x}</option>)}</select><select className='border p-2 w-full' value={logForm.isDeal?'1':'0'} onChange={e=>setLogForm({...logForm,isDeal:e.target.value==='1'})}><option value='0'>未成交</option><option value='1'>成交</option></select><input className='border p-2 w-full' placeholder='成交金额(成交时必填)' value={logForm.dealAmount} onChange={e=>setLogForm({...logForm,dealAmount:e.target.value})}/><select className='border p-2 w-full' value={logForm.lostReason} onChange={e=>setLogForm({...logForm,lostReason:e.target.value})}>{(opts.lost_reasons||[]).map((x:string)=><option key={x}>{x}</option>)}</select><input className='border p-2 w-full' placeholder='未成交原因(可选补充)' value={logForm.lostReason} onChange={e=>setLogForm({...logForm,lostReason:e.target.value})}/><button className='bg-green-600 text-white px-3 py-1 rounded' onClick={submitLog}>提交跟进</button></div></div>
  <div className='grid grid-cols-2 gap-3'><div className='bg-white border rounded p-3'><h3>③今日提交情况</h3><ul className='text-sm'>{acts.map((a:any)=><li key={a.id}>{a.staff}：线索{a.leadsAdded} 跟进{a.followupsAdded} 成交{a.dealsAdded}</li>)}</ul></div><div className='bg-white border rounded p-3'><h3>④数据明细</h3><p className='text-sm'>线索 {leads.length} 条，跟进 {logs.length} 条</p></div></div>
  </div>
}
