'use client';
import Link from 'next/link';
import { Bell, Pencil, Plus, Trash2, ArrowUp, ArrowDown } from 'lucide-react';
import { useEffect, useState } from 'react';

const defaults=[['工作台首页','/dashboard'],['今日任务中心','/dashboard/tasks'],['客户管理','/dashboard/customers'],['客户跟进','/dashboard/followups'],['电联管理','/dashboard/calls'],['询单转化','/dashboard/conversions'],['每日销售额数据','/dashboard/daily-sales'],['KPI绩效','/dashboard/kpi'],['老客复购','/dashboard/repurchase'],['评价管理','/dashboard/reviews'],['朋友圈/视频号','/dashboard/social'],['竞品假聊','/dashboard/competitors'],['问题复盘','/dashboard/problems'],['话术素材库','/dashboard/scripts'],['排班管理','/dashboard/schedules'],['任务规则','/dashboard/task-rules'],['用户管理','/dashboard/users'],['今日提交情况','/dashboard/submissions'],['系统设置','/dashboard/settings']];

export default function Layout({children}:{children:React.ReactNode}){
  const [nav,setNav]=useState<any[]>(defaults); const [visible,setVisible]=useState<any[]>(defaults); const [edit,setEdit]=useState(false);
  useEffect(()=>{const c=localStorage.getItem('menu_nav'); const base=c?JSON.parse(c):defaults; setNav(base); const m=document.cookie.match(/(?:^|; )session=([^;]+)/); let u=''; if(m){try{u=JSON.parse(decodeURIComponent(m[1])).name || JSON.parse(decodeURIComponent(m[1])).username || ''}catch{}} fetch('/api/menu-permissions').then(r=>r.json()).then(p=>{const allow=(p[u]||base.map((x:any)=>x[1])); setVisible(base.filter((x:any)=>allow.includes(x[1])))}).catch(()=>setVisible(base));},[]);
  const save=(n:any[])=>{setNav(n); localStorage.setItem('menu_nav',JSON.stringify(n));};
  return <div className='flex min-h-screen'><aside className='w-72 bg-slate-900 text-white p-3 space-y-2'><div className='flex justify-between items-center'><span>菜单管理</span><button onClick={()=>setEdit(!edit)}><Pencil size={14}/></button></div>{(edit?nav:visible).map((n,i)=><div key={i} className='flex items-center gap-1'>{<Link className='block text-sm hover:bg-slate-700 rounded p-2 flex-1' href={n[1]}>{n[0]}</Link>}{edit&&<><button onClick={()=>{const t=[...nav]; if(i>0){[t[i-1],t[i]]=[t[i],t[i-1]];save(t);}}}><ArrowUp size={12}/></button><button onClick={()=>{const t=[...nav]; if(i<nav.length-1){[t[i+1],t[i]]=[t[i],t[i+1]];save(t);}}}><ArrowDown size={12}/></button><button onClick={()=>{const name=prompt('新名称',n[0]);if(name){const t=[...nav];t[i]=[name,n[1]];save(t);}}><Pencil size={12}/></button><button onClick={()=>save(nav.filter((_,idx)=>idx!==i))}><Trash2 size={12}/></button></>}</div>)}{edit&&<button className='text-xs mt-2 bg-slate-700 px-2 py-1 rounded' onClick={()=>{const name=prompt('菜单名称');const path=prompt('路由(如 /dashboard/new)');if(name&&path)save([...nav,[name,path]]);}}><Plus size={12} className='inline'/> 添加菜单</button>}</aside><div className='flex-1'><header className='h-14 border-b bg-white px-4 flex items-center justify-between'><div>欧信售前客服作战台</div><div className='flex gap-4 text-sm'><span>{new Date().toLocaleDateString('zh-CN')}</span><span>当前班次: 白班</span><Bell size={16}/><a href='/login'>退出</a></div></header><main className='p-4'>{children}</main></div></div>;
}
